"""Add frontend_summary to projects

Revision ID: 496a954ea5db
Revises: 701768f4a73d
Create Date: 2025-11-08 04:19:52.266137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496a954ea5db'
down_revision: Union[str, Sequence[str], None] = '701768f4a73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('frontend_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'frontend_summary')
    # ### end Alembic commands ###
