"""Create project table

Revision ID: 701768f4a73d
Revises: 
Create Date: 2025-11-03 05:01:44.251524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '701768f4a73d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('initial_idea', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BLUEPRINTING', 'SIMULATING', 'COMPLETE', 'FAILED', name='projectstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('initial_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stressed_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('premortem_report', sa.Text(), nullable=True),
    sa.Column('trello_board_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
